clickhouse:
  image: yandex/clickhouse-server:20.8.12.2
  volumes:
  - "./rollup.xml:/etc/clickhouse-server/config.d/rollup.xml"
  - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
  - "./data/clickhouse/data:/var/lib/clickhouse/data"
  - "./data/clickhouse/metadata:/var/lib/clickhouse/metadata"
carbon-clickhouse:
  image: lomik/carbon-clickhouse:v0.11.1
  volumes:
  - "./data/carbon-clickhouse:/data/carbon-clickhouse"
  - "./carbon-clickhouse.conf:/etc/carbon-clickhouse/carbon-clickhouse.conf"
  ports:
  - "2003:2003" # plain tcp
  - "2003:2003/udp" # plain udp
  - "2004:2004" # pickle
  - "2006:2006" # prometheus remote write
  links:
  - clickhouse
graphite-clickhouse:
  image: lomik/graphite-clickhouse:v0.12.0
  volumes:
  - "./rollup.xml:/etc/graphite-clickhouse/rollup.xml"
  - "./graphite-clickhouse.conf:/etc/graphite-clickhouse/graphite-clickhouse.conf"
  links:
  - clickhouse
carbonapi:
  image: gographite/carbonapi:v0.15.2
  volumes:
  - "./carbonapi.yaml:/etc/carbonapi.yaml"
  ports:
  -"8081:8081"
  links:
  - graphite-clickhouse
